### ISSUE TITLE
Cant install library with pip install

### ISSUE THREAD

**Issue by fgvbrt** [PhilipVinc/mpi4jax#39]
Here is error that I got. I would appreciate any help:
```Collecting mpi4jax
  Using cached mpi4jax-0.2.9.tar.gz (77 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python /opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpom_c2opr
       cwd: /tmp/pip-install-gw9cocxc/mpi4jax_75a4d080aa3d4d6fb3f18bd923521a35
  Complete output (67 lines):
  Compiling mpi4jax/cython/mpi_xla_bridge.pyx because it depends on /tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/Cython/Includes/libc/stdint.pxd.
  Compiling mpi4jax/cython/mpi_xla_bridge_cpu.pyx because it depends on /tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/Cython/Includes/libc/string.pxd.
  Compiling mpi4jax/cython/mpi_xla_bridge_gpu.pyx because it changed.
  [1/3] Cythonizing mpi4jax/cython/mpi_xla_bridge_gpu.pyx
  warning: mpi4jax/cython/mpi_xla_bridge_gpu.pyx:189:43: local variable 'count' referenced before assignment

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              checked_cuda_memcpy(buf, data, count, cudaMemcpyDeviceToHost)
      else:
          if rank == root:
              checked_cuda_memcpy(buf, data, count, cudaMemcpyDeviceToDevice)

      mpi_xla_bridge.mpi_bcast(buf, nitems, dtype, op, comm, token)
                                                  ^
  ------------------------------------------------------------

  mpi4jax/cython/mpi_xla_bridge_gpu.pyx:191:49: undeclared name not builtin: op

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              checked_cuda_memcpy(buf, data, count, cudaMemcpyDeviceToHost)
      else:
          if rank == root:
              checked_cuda_memcpy(buf, data, count, cudaMemcpyDeviceToDevice)

      mpi_xla_bridge.mpi_bcast(buf, nitems, dtype, op, comm, token)
                                                  ^
  ------------------------------------------------------------

  mpi4jax/cython/mpi_xla_bridge_gpu.pyx:191:49: Coercion from Python not allowed without the GIL

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              checked_cuda_memcpy(buf, data, count, cudaMemcpyDeviceToHost)
      else:
          if rank == root:
              checked_cuda_memcpy(buf, data, count, cudaMemcpyDeviceToDevice)

      mpi_xla_bridge.mpi_bcast(buf, nitems, dtype, op, comm, token)
                                                  ^
  ------------------------------------------------------------

  mpi4jax/cython/mpi_xla_bridge_gpu.pyx:191:49: Accessing Python global or builtin not allowed without gil
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 168, in <module>
      language_level=3,
    File "/tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-ml2cy_fw/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: mpi4jax/cython/mpi_xla_bridge_gpu.pyx
  ----------------------------------------
```

**Comment by fgvbrt** [comment]
count is not assigned here:
https://github.com/PhilipVinc/mpi4jax/blob/master/mpi4jax/cython/mpi_xla_bridge_gpu.pyx#L189
op is not defined here:
https://github.com/PhilipVinc/mpi4jax/blob/master/mpi4jax/cython/mpi_xla_bridge_gpu.pyx#L191

**Comment by PhilipVinc** [comment]
Damn.
It's just a typo because i could not test the last PR with broadcast on a gpu rig...

I'll fix it ASAP
