### ISSUE TITLE
Weird test failure on GPU/CUDA

### ISSUE THREAD

**Issue by PhilipVinc** [PhilipVinc/mpi4jax#42]
I'm seeing most test failing on GPU/CUDA and rarely on CPU with error

```
/home/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/cython/__init__.py:44: UserWarning: Not using CUDA-enabled MPI. If you are sure that your MPI library is built with CUDA support, set MPI4JAX_USE_CUDA_MPI=1. To silence this warning, set MPI4JAX_USE_CUDA_MPI=0.
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File "/tmp/pytest-of-filippovicentini/pytest-5/test_abort_on_error0/abort.py", line 24, in <module>
    send_jit(jnp.ones(10))
jax._src.traceback_util.FilteredStackTrace: RuntimeError: Internal: Unexpected shape kind for %after-all.3 = token[] after-all(), metadata={op_type="create_token" op_name="jit(send_jit)/create_token" source_file="/home/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/collective_ops/send.py" source_line=57} and shape index {}

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/pytest-of-filippovicentini/pytest-5/test_abort_on_error0/abort.py", line 24, in <module>
    send_jit(jnp.ones(10))
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/api.py", line 398, in f_jitted
    return cpp_jitted_f(context, *args, **kwargs)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/api.py", line 289, in cache_miss
    out_flat = xla.xla_call(
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/core.py", line 1275, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/core.py", line 1266, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/core.py", line 1278, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/core.py", line 631, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/interpreters/xla.py", line 580, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/linear_util.py", line 260, in memoized_fun
    ans = call(fun, *args)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/interpreters/xla.py", line 727, in _xla_callable
    compiled = backend_compile(backend, built, options)
  File "/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/interpreters/xla.py", line 352, in backend_compile
    return backend.compile(built_c, compile_options=options)
RuntimeError: Internal: Unexpected shape kind for %after-all.3 = token[] after-all(), metadata={op_type="create_token" op_name="jit(send_jit)/create_token" source_file="/home/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/collective_ops/send.py" source_line=57} and shape index {}
```

It is maybe related by how we pass forward the tokens?

**Comment by PhilipVinc** [comment]
Duplicate of #40
